/*
 Generated by typeshare 1.13.3
*/


/** Represents the type of a communication channel. */
export enum ChannelType {
	/** A group channel, typically used for multi-user conversations. */
	Group = "group",
	/** A direct message channel, used for one-on-one conversations. */
	Direct = "direct",
	/** A private channel, used for restricted or hidden conversations. */
	Private = "private",
}

/**
 * Represents a communication channel with a unique ID, type, name, and
 * optional parent ID.
 * 
 * # Fields
 * - `id`: Unique identifier for the channel. If the platform cannot provide a
 * user ID, the event ID is used.
 * - `ty`: Type of the channel (`group`, `direct`, or `private`).
 * - `name`: Display name of the channel. If the platform cannot provide a
 * nickname, the `id` is used.
 * - `parent_id`: Optional parent channel ID, used for nested channels (e.g.,
 * subgroups).
 */
export interface Channel {
	id: string;
	type: ChannelType;
	name: string;
	parent_id?: string;
}

