/*
 Generated by typeshare 1.13.3
*/


export interface Message<Seg> {
	id: string;
	content: Seg[];
}

export interface Segment {
	type: string;
	data: any;
}

export interface SendMessage {
	content: Segment[];
}

