/*
 Generated by typeshare 1.13.3
*/


export enum SegmentType {
	Text = "text",
	Image = "image",
	Unknown = "unknown",
}

export interface Segment {
	type: SegmentType;
	content: string;
}

export interface Message {
	id: string;
	content: Segment[];
}

export interface SendMessage {
	content: Segment[];
}

