/*
 Generated by typeshare 1.13.3
*/


export interface Segment {
	type: string;
	content: string;
}

export interface Message {
	id: string;
	content: Segment[];
}

export interface SendMessage {
	content: Segment[];
}

